[project]
name = "roolz"
version = "0.1.0"
description = "A JSON-based rule engine for python"
authors = [
    {name = "Dje", email = "bfodje@gmail.com"}
]
readme = "README.md"
dependencies = []
requires-python = ">=3.11"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-cov>=6.0.0",
    "pytest-benchmark>=4.0.0",
    "ruff>=0.6.8",
    "pytest-xdist>=3.8.0",
]
